//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int bill_id { get; set; }
        public Nullable<int> pat_id { get; set; }
        public double doctor_charge { get; set; }
        public double med_charge { get; set; }
        public Nullable<double> room_charge { get; set; }
        public Nullable<int> no_of_days { get; set; }
        public double total_bill { get; set; }
        public string pat_type { get; set; }
        public string pat_name { get; set; }
        public Nullable<System.DateTime> admit_date { get; set; }
        public Nullable<System.DateTime> leave_date { get; set; }
        public string doc_name { get; set; }
    }
}
