//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Doctors = new HashSet<Doctor>();
            this.Nurses = new HashSet<Nurse>();
        }
    
        public int emp_id { get; set; }
        public string emp_firstname { get; set; }
        public string emp_lastname { get; set; }
        public System.DateTime emp_dob { get; set; }
        public int emp_salary { get; set; }
        public string emp_gender { get; set; }
        public string emp_phone { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Nurse> Nurses { get; set; }
    }
}
