//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndoorPatient
    {
        public int indpat_id { get; set; }
        public string indpat_disease { get; set; }
        public string indpat_status { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<int> pat_id { get; set; }
        public System.DateTime admit_date { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Room Room { get; set; }
    }
}
