//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public Medicine()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int med_id { get; set; }
        public string med_name { get; set; }
        public double med_price { get; set; }
    
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
