//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nurse
    {
        public Nurse()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int nurse_id { get; set; }
        public string nurse_experience { get; set; }
        public int emp_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
