//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int presc_id { get; set; }
        public string presc_dosage { get; set; }
        public Nullable<int> med_id { get; set; }
        public Nullable<int> pat_id { get; set; }
        public Nullable<int> doc_id { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
